'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class nklKhoa
    Public Property NklMaKH As String
    Public Property NklTenKH As String
    Public Property NklTrangThai As Nullable(Of Boolean)

    Public Overridable Property nklSinhVien As ICollection(Of nklSinhVien) = New HashSet(Of nklSinhVien)

End Class
