'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class nklSinhVien
    Public Property NklMaSV As String
    Public Property NklHoSV As String
    Public Property NklNgaySinh As Nullable(Of Date)
    Public Property NklPhai As Nullable(Of Boolean)
    Public Property NklPhone As String
    Public Property NkllEmail As String
    Public Property NklMaKH As String

    Public Overridable Property nklKhoa As nklKhoa

End Class
